-- =============================================================================
-- Migration Entity Framework - FleetSyncManager
-- =============================================================================
-- Script généré pour Entity Framework Core 9.0.8
-- Compatible avec Npgsql.EntityFrameworkCore.PostgreSQL
-- =============================================================================

-- Vérification et création de la base de données
SELECT 'CREATE DATABASE fleetsync_dev OWNER fleetsync_user' 
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'fleetsync_dev');

\c fleetsync_dev;

-- Extensions requises
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================================================
-- Migration: 20250828000001_InitialCreate
-- =============================================================================

-- Tables Identity (compatibles EF Core)
CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

-- Tables Domain
CREATE TABLE "Drivers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "Email" character varying(255) NOT NULL,
    "PhoneNumber" character varying(20),
    "LicenseNumber" character varying(50) NOT NULL,
    "LicenseType" integer NOT NULL,
    "LicenseExpiryDate" timestamp with time zone NOT NULL,
    "HireDate" timestamp with time zone NOT NULL,
    "Status" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    CONSTRAINT "PK_Drivers" PRIMARY KEY ("Id")
);

CREATE TABLE "Vehicles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "LicensePlate" character varying(20) NOT NULL,
    "Vin" character varying(17),
    "Brand" character varying(50) NOT NULL,
    "Model" character varying(50) NOT NULL,
    "Year" integer NOT NULL,
    "FuelType" integer NOT NULL,
    "CurrentMileage" integer NOT NULL,
    "Status" integer NOT NULL,
    "PurchaseDate" timestamp with time zone,
    "PurchasePrice" numeric(12,2),
    "InsurancePolicyNumber" character varying(100),
    "InsuranceExpiryDate" timestamp with time zone,
    "NextMaintenanceDue" timestamp with time zone,
    "NextMaintenanceMileage" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    CONSTRAINT "PK_Vehicles" PRIMARY KEY ("Id")
);

CREATE TABLE "VehicleAssignments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "VehicleId" integer NOT NULL,
    "DriverId" integer NOT NULL,
    "AssignedDate" timestamp with time zone NOT NULL,
    "UnassignedDate" timestamp with time zone,
    "IsActive" boolean NOT NULL,
    "Notes" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    CONSTRAINT "PK_VehicleAssignments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_VehicleAssignments_Drivers_DriverId" FOREIGN KEY ("DriverId") REFERENCES "Drivers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_VehicleAssignments_Vehicles_VehicleId" FOREIGN KEY ("VehicleId") REFERENCES "Vehicles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "MaintenanceRecords" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "VehicleId" integer NOT NULL,
    "MaintenanceType" integer NOT NULL,
    "Description" text NOT NULL,
    "MaintenanceDate" timestamp with time zone NOT NULL,
    "MileageAtMaintenance" integer NOT NULL,
    "Cost" numeric(10,2),
    "ServiceProvider" character varying(200),
    "NextMaintenanceDue" timestamp with time zone,
    "NextMaintenanceMileage" integer,
    "Status" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    CONSTRAINT "PK_MaintenanceRecords" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MaintenanceRecords_Vehicles_VehicleId" FOREIGN KEY ("VehicleId") REFERENCES "Vehicles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Incidents" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "VehicleId" integer NOT NULL,
    "DriverId" integer,
    "IncidentType" integer NOT NULL,
    "Severity" integer NOT NULL,
    "Description" text NOT NULL,
    "IncidentDate" timestamp with time zone NOT NULL,
    "Location" character varying(500),
    "PoliceReportNumber" character varying(100),
    "InsuranceClaimNumber" character varying(100),
    "EstimatedCost" numeric(12,2),
    "ActualCost" numeric(12,2),
    "Status" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    CONSTRAINT "PK_Incidents" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Incidents_Drivers_DriverId" FOREIGN KEY ("DriverId") REFERENCES "Drivers" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Incidents_Vehicles_VehicleId" FOREIGN KEY ("VehicleId") REFERENCES "Vehicles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "GpsTrackingRecords" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "VehicleId" integer NOT NULL,
    "Latitude" numeric(10,8) NOT NULL,
    "Longitude" numeric(11,8) NOT NULL,
    "Altitude" numeric(8,2),
    "Speed" numeric(6,2),
    "Heading" numeric(5,2),
    "RecordedAt" timestamp with time zone NOT NULL,
    "DeviceId" character varying(100),
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_GpsTrackingRecords" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GpsTrackingRecords_Vehicles_VehicleId" FOREIGN KEY ("VehicleId") REFERENCES "Vehicles" ("Id") ON DELETE CASCADE
);

-- Index obligatoires pour Identity
CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

-- Index pour les foreign keys (requis par EF Core)
CREATE INDEX "IX_VehicleAssignments_DriverId" ON "VehicleAssignments" ("DriverId");
CREATE INDEX "IX_VehicleAssignments_VehicleId" ON "VehicleAssignments" ("VehicleId");
CREATE INDEX "IX_MaintenanceRecords_VehicleId" ON "MaintenanceRecords" ("VehicleId");
CREATE INDEX "IX_Incidents_DriverId" ON "Incidents" ("DriverId");
CREATE INDEX "IX_Incidents_VehicleId" ON "Incidents" ("VehicleId");
CREATE INDEX "IX_GpsTrackingRecords_VehicleId" ON "GpsTrackingRecords" ("VehicleId");

-- Index uniques pour les contraintes métier
CREATE UNIQUE INDEX "IX_Drivers_Email" ON "Drivers" ("Email");
CREATE UNIQUE INDEX "IX_Drivers_LicenseNumber" ON "Drivers" ("LicenseNumber");
CREATE UNIQUE INDEX "IX_Vehicles_LicensePlate" ON "Vehicles" ("LicensePlate");

-- Index de performance
CREATE INDEX "IX_Vehicles_Status" ON "Vehicles" ("Status");
CREATE INDEX "IX_Vehicles_NextMaintenanceDue" ON "Vehicles" ("NextMaintenanceDue");
CREATE INDEX "IX_Drivers_Status" ON "Drivers" ("Status");
CREATE INDEX "IX_Drivers_LicenseExpiryDate" ON "Drivers" ("LicenseExpiryDate");
CREATE INDEX "IX_GpsTrackingRecords_RecordedAt" ON "GpsTrackingRecords" ("RecordedAt");

-- =============================================================================
-- Table de migration EF Core
-- =============================================================================

CREATE TABLE "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

-- Enregistrement de cette migration
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250828000001_InitialCreate', '9.0.8');

-- =============================================================================
-- Données initiales
-- =============================================================================

-- Rôles par défaut
INSERT INTO "AspNetRoles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp")
VALUES 
    ('admin-role-id', 'Admin', 'ADMIN', 'admin-concurrency-stamp'),
    ('manager-role-id', 'Manager', 'MANAGER', 'manager-concurrency-stamp'),
    ('user-role-id', 'User', 'USER', 'user-concurrency-stamp');

COMMIT;
